import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Shopn!</h1>

        <p className={styles.description}>
          A simple e-commerce website built with <em>Next.js</em> and{" "}
          <em>Stripe</em>.
        </p>

        <ul className={styles.grid}>
          <li className={styles.card}>
            <a href="https://nextjs.org/docs">
              <img src="/images/sticker.png" alt="Sticker" />
              <h2>Stickers</h2>
              <p>Find the best stickers in the web with Shopn!</p>
            </a>
          </li>

          <li className={styles.card}>
            <a href="https://github.com/vercel/next.js/tree/canary/examples">
              <img src="/images/tshirt.png" alt="TShirt" />
              <h2>TShirt</h2>
              <p>Grab these limited edition T-Shirts.</p>
            </a>
          </li>

          <li className={styles.card}>
            <a href="https://nextjs.org/learn">
              <img src="/images/combo.png" alt="Combo" />
              <h2>Combo</h2>
              <p>
                Show your love for Shopn with a tshirt and sticker combo pack!
              </p>
            </a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
